apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        volumeMounts:
          - mountPath: /data/db
            name: mo-data
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: ""
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: ""
      volumes:
      - name: mo-data
        persistentVolumeClaim:
          claimName: mo-data-pvc
      restartPolicy: Always