apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mosquitto 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      name: mosquitto
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: ""
        ports:
        - containerPort: 1883