apiVersion: v1
kind: Pod
metadata: 
  name: pod-django
  labels: 
    app: pod-test-v1.0 
spec:
  containers: 
    - name: django
      image: #montar pela dockerfile
      ports:
        - containerPort: 5000    
      volumeMounts:
        - mountPath: /volume-django
          name: volume-test

  volumes:
    - name: volume-test
      hostPath:
        path: #########
        type: Directory