apiVersion: v1
kind: Pod
metadata: 
  name: pod-mosquitto
  labels: 
    app: pod-test-v1.0  
spec:
  containers: 
    - name: mosquitto
      image: #montar pela dockerfile
      ports:
        - containerPort: 8883 